In [1]:
class Queue:
    def __init__(self):
        self.queue = []

    def is_empty(self):
        return len(self.queue) == 0

    def enqueue(self, item):
        self.queue.append(item)

    def dequeue(self):
        if self.is_empty():
            raise IndexError("Dequeue from an empty queue")
        return self.queue.pop(0)

    def peek(self):
        if self.is_empty():
            raise IndexError("Peek from an empty queue")
        return self.queue[0]

    def size(self):
        return len(self.queue)

# Example usage:
q = Queue()
q.enqueue(1)
q.enqueue(2)
q.enqueue(3)
print(q.dequeue())  # Output: 1
print(q.peek())     # Output: 2
print(q.size())     # Output: 2

1
2
2


### Adjacency Matrix

In [2]:
import numpy as np

# Define the adjacency matrix
adj_matrix = np.array([
    [0, 1, 0, 0, 0, 1],  # A
    [1, 0, 1, 0, 0, 0],  # B
    [0, 1, 0, 1, 0, 0],  # C
    [0, 0, 1, 0, 1, 0],  # D
    [0, 0, 0, 1, 0, 1],  # E
    [1, 0, 0, 0, 1, 0]   # F
])

# Print the adjacency matrix
print("Adjacency Matrix:")
print(adj_matrix)


Adjacency Matrix:
[[0 1 0 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]
 [0 0 1 0 1 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]]


### Adjacency List

In [3]:
class Graph:
    def __init__(self):
        self.graph = {}

    def add_edge(self, u, v):
        if u not in self.graph:
            self.graph[u] = []
        if v not in self.graph:
            self.graph[v] = []

        self.graph[u].append(v)
        self.graph[v].append(u)

    def display_graph(self):
        for node in self.graph:
            print(f"{node} -> {self.graph[node]}")


# Create a graph object
graph = Graph()

# Add edges
graph.add_edge('A', 'B')
graph.add_edge('A', 'C')
graph.add_edge('B', 'C')
graph.add_edge('B', 'D')
graph.add_edge('E', 'F')
graph.add_edge('C', 'F')
graph.add_edge('D', 'E')

# Display the graph
graph.display_graph()


A -> ['B', 'C']
B -> ['A', 'C', 'D']
C -> ['A', 'B', 'F']
D -> ['B', 'E']
E -> ['F', 'D']
F -> ['E', 'C']


### Breadth First Search

Hrizontal triverse

Always use Queue; as we need first in first out.

**Black:** Node stored in visited list

**Gray:** Node stored in Queue

**White:** New node

In [4]:
def bfs(graph, start):
    visited = set()
    queue = Queue()
    queue.enqueue(start)
    visited.add(start)

    while not queue.is_empty():
        node = queue.dequeue()
        print(node, end=' ')

        for neighbour in graph[node]:
            if neighbour not in visited:
                queue.enqueue(neighbour)
                visited.add(neighbour)

In [5]:
visited = ["S", "R", "V", "W", "T", "X", "U", "Y"]

# Create a graph object
graph = Graph()

# Add edges
graph.add_edge('S', 'R')
graph.add_edge('S', 'W')
graph.add_edge('R', 'V')
graph.add_edge('W', 'T')
graph.add_edge('W', 'X')
graph.add_edge('T', 'X')
graph.add_edge('T', 'U')
graph.add_edge('X', 'U')
graph.add_edge('X', 'Y')
graph.add_edge('U', 'Y')

# Display the graph
graph.display_graph()


S -> ['R', 'W']
R -> ['S', 'V']
W -> ['S', 'T', 'X']
V -> ['R']
T -> ['W', 'X', 'U']
X -> ['W', 'T', 'U', 'Y']
U -> ['T', 'X', 'Y']
Y -> ['X', 'U']


In [6]:
class Graph:
    def __init__(self):
        self.graph = {}

    def add_edge(self, u, v):
        if u not in self.graph:
            self.graph[u] = []
        if v not in self.graph:
            self.graph[v] = []
       
        self.graph[u].append(v)
        self.graph[v].append(u)  

    def display_graph(self):
        for node in self.graph:
            print(f"{node} -> {self.graph[node]}")
   
    def bfs(self, start):
        visited = set()
       
        queue = Queue()
       
        queue.enqueue(start)
        visited.add(start)
       
        bfs_result = []
       
        while not queue.is_empty():
            node = queue.dequeue()
            bfs_result.append(node)
           
            for neighbor in self.graph[node]:
                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.enqueue(neighbor)
       
        return bfs_result


class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class Queue:
    def __init__(self):
        self.front = None
        self.rear = None
        self.size = 0

    def enqueue(self, data):
        new_node = Node(data)
        if self.rear is None:
            self.front = self.rear = new_node
        else:
            self.rear.next = new_node
            self.rear = new_node
        self.size += 1

    def dequeue(self):
        if self.is_empty():
            raise IndexError("Dequeue from an empty queue")
        dequeued_data = self.front.data
        self.front = self.front.next
        if self.front is None:
            self.rear = None
        self.size -= 1
        return dequeued_data

    def peek(self):
        if self.is_empty():
            raise IndexError("Peek from an empty queue")
        return self.front.data

    def is_empty(self):
        return self.front is None

    def get_size(self):
        return self.size



g = Graph()

g.add_edge(1, 2)
g.add_edge(1, 4)
g.add_edge(2, 4)
g.add_edge(3, 5)
g.add_edge(4, 5)

print("Graph:")
g.display_graph()

print("\nBFS traversal starting from node 1:")
bfs_result = g.bfs(1)
print(bfs_result)  

Graph:
1 -> [2, 4]
2 -> [1, 4]
4 -> [1, 2, 5]
3 -> [5]
5 -> [3, 4]

BFS traversal starting from node 1:
[1, 2, 4, 5, 3]
