In [ ]:
class Queue:
    def __init__(self):
        self.queue = []

    def is_empty(self):
        return len(self.queue) == 0

    def enqueue(self, item):
        self.queue.append(item)

    def dequeue(self):
        if self.is_empty():
            raise IndexError("Dequeue from an empty queue")
        return self.queue.pop(0)

    def peek(self):
        if self.is_empty():
            raise IndexError("Peek from an empty queue")
        return self.queue[0]

    def size(self):
        return len(self.queue)

# Example usage:
q = Queue()
q.enqueue(1)
q.enqueue(2)
q.enqueue(3)
print(q.dequeue())  # Output: 1
print(q.peek())     # Output: 2
print(q.size())     # Output: 2

### Adjacency Matrix

In [1]:
import numpy as np

# Define the adjacency matrix
adj_matrix = np.array([
    [0, 1, 0, 0, 0, 1],  # A
    [1, 0, 1, 0, 0, 0],  # B
    [0, 1, 0, 1, 0, 0],  # C
    [0, 0, 1, 0, 1, 0],  # D
    [0, 0, 0, 1, 0, 1],  # E
    [1, 0, 0, 0, 1, 0]   # F
])

# Print the adjacency matrix
print("Adjacency Matrix:")
print(adj_matrix)


Adjacency Matrix:
[[0 1 0 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]
 [0 0 1 0 1 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]]


### Adjacency List

In [8]:
class Graph:
    def __init__(self):
        self.graph = {}

    def add_edge(self, u, v):
        if u not in self.graph:
            self.graph[u] = []
        if v not in self.graph:
            self.graph[v] = []

        self.graph[u].append(v)
        self.graph[v].append(u)

    def display_graph(self):
        for node in self.graph:
            print(f"{node} -> {self.graph[node]}")


# Create a graph object
graph = Graph()

# Add edges
graph.add_edge('A', 'B')
graph.add_edge('A', 'C')
graph.add_edge('B', 'C')
graph.add_edge('B', 'D')
graph.add_edge('E', 'F')
graph.add_edge('C', 'F')
graph.add_edge('D', 'E')

# Display the graph
graph.display_graph()


A -> ['B', 'C']
B -> ['A', 'C', 'D']
C -> ['A', 'B', 'F']
D -> ['B', 'E']
E -> ['F', 'D']
F -> ['E', 'C']
